/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factorial.gradle;

public class FactorialFinder {
    public int calculateFactorial(int number) {
        int result = 1;
        if (number == 0 || number == 1) return result;

        for (int x = 1; x <= number; x++) result *= x;
        return result;
    }
}
